version: '3.9'
services:

  nuchal_db:
    env_file:
      - .env
    container_name: nuchal_db
    image: postgres:alpine
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  pgdata: