version: '3.9'
services:
  db:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=somePassword
      - POSTGRES_DB=nuchal
      - POSTGRES_PORT=5432
      - POSTGRES_HOST=localhost
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    network_mode: bridge

volumes:
  pgdata: