version: '3'
services:
  sim:
    depends_on:
      - db
    build:
      context: ../../
      dockerfile: docker/sim/Dockerfile
    ports:
      - 8089:8089
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: