version: '3'

services:
  user:
    container_name: user
    image: nuchal-user:v1.0.0
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/user/Dockerfile
    networks:
      - local
  sim:
    container_name: sim
    image: nuchal-sim:v1.0.0
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/sim/Dockerfile
    ports:
      - 127.0.0.1:8089:8089
    networks:
      - local
  trade:
    container_name: trade
    image: trade-sim:v1.0.0
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/trade/Dockerfile
    networks:
      - local
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local

volumes:
  pgdata:

networks:
  local:
    external: false
    name: local