version: '3'
services:
  user:
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/user/Dockerfile
    networks:
      - local

  sim:
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/sim/Dockerfile
    ports:
      - 8089:8089
    networks:
      - local

  trade:
    env_file:
      - .env
    depends_on:
      - db
    build:
      context: ../
      dockerfile: docker/trade/Dockerfile
    networks:
      - local

  db:
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - local

volumes:
  pgdata:

networks:
  local:
    external: true